baseurl: "/prog-students" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://htc-ccis1515.github.io/" # the base hostname & protocol for your site
title: "CCIS1515 Programming Overview"

exclude:
  - "README.md"
  - "Gemfile"
